const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#5865f2",
    background: "#f2f3f5",
    foreground: "#0a0a0a",
    card: "#ffffff",
    cardForeground: "#0a0a0a",
    primary: "#5865f2",
    primaryForeground: "#ffffff",
    secondary: "#e9eaf0",
    secondaryForeground: "#1a1a1a",
    muted: "#ebedf0",
    mutedForeground: "#737373",
    accent: "#e9eaf0",
    accentForeground: "#1a1a1a",
    destructive: "#ed4245",
    destructiveForeground: "#ffffff",
    border: "#e1e2e6",
    input: "#e1e2e6",
    success: "#3ba55d",
    warning: "#faa61a",
  },
  dark: {
    text: "#dcddde",
    tint: "#5865f2",
    background: "#202225",
    foreground: "#dcddde",
    card: "#2f3136",
    cardForeground: "#dcddde",
    primary: "#5865f2",
    primaryForeground: "#ffffff",
    secondary: "#36393f",
    secondaryForeground: "#dcddde",
    muted: "#36393f",
    mutedForeground: "#72767d",
    accent: "#4f545c",
    accentForeground: "#dcddde",
    destructive: "#ed4245",
    destructiveForeground: "#ffffff",
    border: "#40444b",
    input: "#40444b",
    success: "#3ba55d",
    warning: "#faa61a",
  },
  radius: 8,
};

export default colors;
